from Config import A2C_CFG, ENV_CFG, ICM_CFG

HYPERPARAMS = {
"Seed": ENV_CFG.SEED,
"Action_space_size": ENV_CFG.ACTION_SPACE_SIZE, 
"Device": ENV_CFG.DEVICE,
"Resized_size": ENV_CFG.RESIZED_SIZE,
"Temporal channels": ENV_CFG.TEMPORAL_CHANNELS,
"Action skip value": ENV_CFG.ACTION_SKIP,
"FPS of video": ENV_CFG.FPS,
"Learning rate of A2C": A2C_CFG.LR,
"Number_of_steps": A2C_CFG.NUM_STEPS,
"Number of parallel agents": A2C_CFG.NUM_AGENTS,
"Gamma": A2C_CFG.GAMMA,
"GAE_lambda": A2C_CFG.GAE_LAMBDA,
"Entropy_coefficient": A2C_CFG.ENTROPY_COEF,
"Value_loss_coeficient": A2C_CFG.VALUE_LOSS_COEF,
"Maximum_grad_norm": A2C_CFG.MAX_GRAD_NORM,
"Use rms prop": A2C_CFG.RMS_PROP,
"Hidden neurons in policy": A2C_CFG.POLICY_NEURONS,
"Hidden neurons in value function": A2C_CFG.VALUE_NEURONS,
"ETA ICM - multiplier of reward": ICM_CFG.ETA,
"BETA ICM - weighted sum of forward model and backward model loss": ICM_CFG.BETA,
"Hidden neurons in linear layer of all models in ICM": ICM_CFG.HIDDEN_LAYERS,
"FMAP QTY in all convolutional layers": ICM_CFG.FMAP_QTY,
"Learn ICM only on latest batch. If true, buffer size and batch size are irrelevant": ICM_CFG.SAVE_LATEST,
"Buffer size of ICM buffer": ICM_CFG.BUFFER_SIZE,
"Batch size of ICM buffer": ICM_CFG.BATCH_SIZE,
"Learning rate of ICM": ICM_CFG.LR,}